# Generated by Django 3.2.15 on 2022-10-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_de_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='fecha_de_entrega',
            field=models.DateField(null=True),
        ),
    ]
