# Generated by Django 3.2.15 on 2022-10-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_auto_20221009_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='entregado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
    ]
