# Generated by Django 3.2.15 on 2022-10-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_auto_20221010_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='apelldio',
            new_name='apellido',
        ),
    ]
