# Generated by Django 3.2.15 on 2022-10-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0004_rename_apelldio_profesor_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apelldio',
            new_name='apellido',
        ),
    ]
