# Generated by Django 3.2.15 on 2022-10-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_rename_apelldio_estudiante_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='corre@correo.com', max_length=30),
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default='corre@correo.com', max_length=30),
        ),
    ]
