# Generated by Django 3.2.15 on 2022-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0006_auto_20221010_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
