# Generated by Django 3.2.15 on 2022-10-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0007_entregable_entregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha_de_entrega',
        ),
    ]
